[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/elliotchance/tf"
  version = "^1.5.0"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  version = "^1.0.27"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"
